import type { AddOn, RoomCharge, CheckInDetails, Booking } from '@/lib/types/booking';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function dbToBooking(row: Record<string, any>): Booking {
  return {
    id: row['id'] as string,
    confirmationNumber: row['confirmation_number'] as string,
    guestName: row['guest_name'] as string,
    contactNumber: row['contact_number'] as string,
    email: (row['email'] as string | null) ?? '',
    companyName: (row['company_name'] as string | null) ?? '',
    gstNumber: (row['gst_number'] as string | null) ?? '',
    arrival: row['arrival'] as string,
    departure: row['departure'] as string,
    nights: row['nights'] as number,
    adults: row['adults'] as number,
    children: row['children'] as number,
    rooms: (row['rooms'] as string[] | null) ?? [],
    rateBreakdown: (row['rate_breakdown'] as string | null) ?? '',
    totalAmount: Number(row['total_amount']),
    addOns: (row['add_ons'] as AddOn[] | null) ?? [],
    roomCharges: (row['room_charges'] as RoomCharge[] | null) ?? [],
    checkInDetails: (row['check_in_details'] as CheckInDetails | null) ?? null,
    advanceRequired: Number(row['advance_required'] ?? 0),
    voucherSent: row['voucher_sent'] === true,
    voucherSentAt: (row['voucher_sent_at'] as string | null) ?? null,
    advancePaid: Number(row['advance_paid']),
    inclusions: (row['inclusions'] as string | null) ?? '',
    remarks: (row['remarks'] as string | null) ?? '',
    specialRequests: (row['special_requests'] as string | null) ?? '',
    createdBy: row['created_by'] as string,
    status: row['status'] as Booking['status'],
    holdExpiresAt: (row['hold_expires_at'] as string | null) ?? null,
    finalBill: (row['final_bill'] as Booking['finalBill']) ?? null,
    createdAt: row['created_at'] as string,
    bookingType: (row['booking_type'] as Booking['bookingType']) ?? 'regular',
    corporateStage: (row['corporate_stage'] as Booking['corporateStage']) ?? null,
    companyAddress: (row['company_address'] as string | null) ?? '',
    companyGST: (row['company_gst'] as string | null) ?? '',
    contactName: (row['contact_name'] as string | null) ?? '',
    contactEmail: (row['contact_email'] as string | null) ?? '',
    guestCount: (row['guest_count'] as Booking['guestCount']) ?? null,
    costSheet: (row['cost_sheet'] as Booking['costSheet']) ?? null,
    proformaInvoice: (row['proforma_invoice'] as Booking['proformaInvoice']) ?? null,
    sourceEnquiryId: (row['source_enquiry_id'] as string | null) ?? null,
    guestId: (row['guest_id'] as string | null) ?? null,
  };
}

export function bookingToDb(b: Booking): Record<string, unknown> {
  return {
    id: b.id,
    confirmation_number: b.confirmationNumber,
    guest_name: b.guestName,
    contact_number: b.contactNumber,
    email: b.email || '',
    company_name: b.companyName || '',
    gst_number: b.gstNumber || '',
    arrival: b.arrival,
    departure: b.departure,
    nights: b.nights,
    adults: b.adults,
    children: b.children,
    rooms: b.rooms || [],
    rate_breakdown: b.rateBreakdown || '',
    total_amount: b.totalAmount || 0,
    // No `?? []` fallback: a partial update that omits these leaves the column undefined,
    // which updateBooking filters out so the existing list is preserved.
    add_ons: b.addOns,
    room_charges: b.roomCharges,
    check_in_details: b.checkInDetails,
    advance_required: b.advanceRequired,
    voucher_sent: b.voucherSent,
    voucher_sent_at: b.voucherSentAt,
    advance_paid: b.advancePaid || 0,
    inclusions: b.inclusions || '',
    remarks: b.remarks || '',
    special_requests: b.specialRequests || '',
    created_by: b.createdBy,
    status: b.status || 'confirmed',
    hold_expires_at: b.holdExpiresAt || null,
    final_bill: b.finalBill || null,
    created_at: b.createdAt,
    booking_type: b.bookingType || 'regular',
    corporate_stage: b.corporateStage || null,
    company_address: b.companyAddress || '',
    company_gst: b.companyGST || '',
    contact_name: b.contactName || '',
    contact_email: b.contactEmail || '',
    guest_count: b.guestCount || null,
    cost_sheet: b.costSheet || null,
    proforma_invoice: b.proformaInvoice || null,
    source_enquiry_id: b.sourceEnquiryId || null,
    guest_id: b.guestId || null,
  };
}
